services:
  bookify-api:
    image: bookify-api
    container_name: bookify-api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    ports:
      - "8080:8080" 
      - "8081:8081"
    depends_on:
      - bookify-db
    
  bookify-db:
    image: postgres:latest
    container_name: bookify-db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
